### ISSUE TITLE
Some question on selection device and card

### ISSUE THREAD

**Issue by alone4u1314** [Meituan-AutoML/MobileVLM#15]
1. Does inference only support Qualcomm series CPUs, and what are the specific requirements for CPU and memory? need Root？
2. Is it possible to use an RTX 4090 during the training phase?
THX

**Comment by alone4u1314** [comment]
What is the performance difference between Snapdragon 888, 8gen1, 8gen2, and 8gen3?
if you guys had done some tests

**Comment by YangYang-DLUT** [comment]
1. For now, our deployment on mobile devices is based on customized`llama.cpp`, you can deploy the inference on Android devices by following our instructions. Technically, you can deploy the inference with customized `llama.cpp` on all of the supported devices of official `llama.cpp` by following the official instructions. There are no basic differences between Qualcomm series CPUs, and 8GB RAM is quite enough. We just measure the latency on Snapdragon 888 and no need to root. 
2. For now it seems like impossible, we us 8*A100 80GB in the training process. I believe with certain framework it might be possible but need a lot of development. Maybe you can looking for plans to train LLaVA on single GPU like RTX 4090 and replace the projector to our LDP structure since we have released the code.

**Comment by er-muyue** [comment]
Hi, we are closing this issue due to the inactivity. Hope your question has been resolved. If you have any further concerns, please feel free to re-open it or open a new issue. Thanks!
